# Generated by Django 5.1.5 on 2025-02-04 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='活動名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='活動描述')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='地點')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日期')),
                ('organizer', models.CharField(blank=True, max_length=255, null=True, verbose_name='主辦單位')),
                ('website', models.URLField(blank=True, null=True, verbose_name='活動網站')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='圖片網址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='資料來源')),
            ],
            options={
                'verbose_name': '活動資訊',
                'verbose_name_plural': '活動資訊',
                'db_table': 'entertainment',
            },
        ),
        migrations.CreateModel(
            name='ImportDates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('import_date', models.DateTimeField(verbose_name='匯入時間')),
                ('timezone_type', models.IntegerField(verbose_name='時區類型')),
                ('timezone', models.CharField(max_length=50, verbose_name='時區')),
            ],
            options={
                'verbose_name': '匯入紀錄',
                'verbose_name_plural': '匯入紀錄列表',
                'db_table': 'import_dates',
            },
        ),
        migrations.CreateModel(
            name='NewTaipeiEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='活動名稱')),
                ('description', models.TextField(blank=True, verbose_name='活動描述')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='地點')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='圖片網址')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='活動來源網址')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='活動分類')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='行政區')),
                ('organizer', models.CharField(blank=True, max_length=255, verbose_name='主辦單位')),
                ('source', models.CharField(default='new_taipei_city', max_length=50, verbose_name='資料來源')),
            ],
            options={
                'verbose_name': '新北市文化活動',
                'verbose_name_plural': '新北市文化活動',
            },
        ),
        migrations.CreateModel(
            name='TaipeiEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='活動名稱')),
                ('description', models.TextField(blank=True, verbose_name='活動描述')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='地點')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='圖片網址')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='活動來源網址')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='活動分類')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='行政區')),
                ('organizer', models.CharField(blank=True, max_length=255, verbose_name='主辦單位')),
                ('price', models.CharField(blank=True, max_length=255, verbose_name='票價資訊')),
                ('source', models.CharField(default='taipei_city', max_length=50, verbose_name='資料來源')),
            ],
            options={
                'verbose_name': '台北市熱門活動',
                'verbose_name_plural': '台北市熱門活動',
            },
        ),
        migrations.CreateModel(
            name='TaiwanCulturalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='活動名稱')),
                ('description', models.TextField(blank=True, verbose_name='活動描述')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='地點')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='圖片網址')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='活動來源網址')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='活動分類')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='地區')),
                ('organizer', models.CharField(blank=True, max_length=255, verbose_name='主辦單位')),
                ('source', models.CharField(default='culture_taiwan', max_length=50, verbose_name='資料來源')),
            ],
            options={
                'verbose_name': '全國綜藝藝文活動',
                'verbose_name_plural': '全國綜藝藝文活動',
            },
        ),
        migrations.CreateModel(
            name='TFAMEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='活動名稱')),
                ('description', models.TextField(blank=True, verbose_name='活動描述')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='地點')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='圖片網址')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='活動來源網址')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('exhibition_type', models.CharField(blank=True, max_length=100, verbose_name='展覽類型')),
                ('artist', models.CharField(blank=True, max_length=255, verbose_name='藝術家')),
                ('admission', models.CharField(blank=True, max_length=255, verbose_name='入場資訊')),
                ('source', models.CharField(default='tfam', max_length=50, verbose_name='資料來源')),
            ],
            options={
                'verbose_name': '北美館展覽',
                'verbose_name_plural': '北美館展覽',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='唯一識別碼')),
                ('activity_name', models.TextField(verbose_name='活動名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='活動描述')),
                ('organizer', models.CharField(blank=True, max_length=200, null=True, verbose_name='主辦單位')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日期')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='地點')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='經度')),
                ('ticket_price', models.TextField(blank=True, null=True, verbose_name='票價資訊')),
                ('related_link', models.TextField(blank=True, null=True, verbose_name='相關連結')),
                ('image_url', models.TextField(blank=True, null=True, verbose_name='圖片網址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '活動資訊',
                'verbose_name_plural': '活動資訊列表',
                'db_table': 'events',
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='events_start_d_92ba55_idx'), models.Index(fields=['location'], name='events_locatio_2a4a74_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryEventRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(verbose_name='顯示順序')),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='theme_entertainment.events', verbose_name='活動ID')),
            ],
            options={
                'verbose_name': '查詢活動關聯',
                'verbose_name_plural': '查詢活動關聯列表',
                'db_table': 'query_event_relations',
            },
        ),
        migrations.CreateModel(
            name='QueryResults',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query_timestamp', models.CharField(max_length=50, verbose_name='查詢時間戳記')),
                ('limit_count', models.IntegerField(verbose_name='限制筆數')),
                ('offset_count', models.IntegerField(verbose_name='位移筆數')),
                ('total_count', models.IntegerField(verbose_name='總筆數')),
                ('sort_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='排序方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('events', models.ManyToManyField(through='theme_entertainment.QueryEventRelations', to='theme_entertainment.events', verbose_name='相關活動')),
            ],
            options={
                'verbose_name': '查詢結果',
                'verbose_name_plural': '查詢結果列表',
                'db_table': 'query_results',
            },
        ),
        migrations.AddField(
            model_name='queryeventrelations',
            name='query_id',
            field=models.ForeignKey(db_column='query_id', on_delete=django.db.models.deletion.CASCADE, to='theme_entertainment.queryresults', verbose_name='查詢ID'),
        ),
        migrations.AlterUniqueTogether(
            name='queryeventrelations',
            unique_together={('query_id', 'event_id')},
        ),
    ]
